functionsDirectory = "C:\\Users\\Admin\\Downloads\\WEPR\\netlify\\functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\Admin\\Downloads\\WEPR"
publishOrigin = "config"
commandOrigin = "config"
command = "npm ci"
functions = "C:\\Users\\Admin\\Downloads\\WEPR\\netlify\\functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
external_node_modules = ["knex", "pg", "better-sqlite3", "mysql2", "mysql", "sqlite3", "tedious", "pg-query-stream", "oracledb"]
included_files = ["views/**", "statics/**"]
node_bundler = "esbuild"

[[headers]]
for = "/statics/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/statics/*"
to = "/statics/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]